#!/bin/bash

TAG="$(git tag --contains HEAD)"
VERSION=v"$(jq -r .version package.json)"

if [[ "$TAG" == "$VERSION" ]]; then
  echo "Tag and version in package.json match!"
  exit 0
else
  echo "Tag and version in package.json don't match!"
  echo "Tag: "$TAG""
  echo "Version: "$VERSION""
  exit 1
fi
